name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-13, ubuntu-22.04]
        addrsize: ["64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew Packages
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: brew install ninja
      - name: Setup Apt Packages
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install ninja-build libvulkan-dev libopengl-dev libglvnd-dev libegl-dev libwayland-dev libxcb-glx0-dev
      - uses: secondlife/action-autobuild@v4
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
